import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "~/utils/api";
import { useRouter } from "next/router";

const Home: NextPage = () => {
    const router = useRouter();

    const createNewGameMutation = api.example.createNewGame.useMutation();

    const sendMessage = async () => {
        const newGame = await createNewGameMutation.mutateAsync();
        await router.push(`/${newGame.slug}`);
    };

    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <button className="bg-slate-300 border border-slate-500 m-4 p-2" onClick={() => void sendMessage()}>SEND</button>
            </main>
        </>
    );
};

export default Home;
